---
- name: Get Server Facts
  hosts: all
  gather_facts: false
  roles:
    - name: osp-facts
      when: os_deploy | default(false) == True

- name: Deploy base configuration
  hosts: frontends:apps:appdbs
  gather_facts: false
  become: true
  roles:
    - { name: base-config, tags: base-config }

- name: setup load-balancer tier
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - { name: lb-tier, tags: [lbs, haproxy] }

- name: setup app tier
  hosts: apps
  become: true
  gather_facts: false
  roles:
    - {name: app-tier, tags: [apps, tomcat]}

- name: setup database tier
  become: true
  hosts: appdbs
  gather_facts: false
  roles:
    - {name: db-tier, tags: [dbs, postgres]}
