---
- name: Get Server Facts
  hosts: all
  gather_facts: false
  roles:
    - name: osp-facts
      when: os_deploy | default(false) == True

- name: setup load-balancer tier
  hosts: frontend
  gather_facts: false
  become: true
  roles:
    - { name: base-config, tags: base-config }
    - { name: lb-tier, tags: [lbs, haproxy] }

- name: setup app tier
  hosts: application
  become: true
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

- name: setup database tier
  become: true
  hosts: database
  gather_facts: false
  tasks:
    - ping:
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
