---
# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    name: "{{ os_name }}"
    image: "{{ os_image }}"
    meta:
      group: "{{ os_meta_group }}"
      deployment_name: "{{ os_meta_deployment_name }}"
    flavor: "{{ os_flavor }}"
    security_groups: "{{ os_security_groups }}"
    key_name: "{{ os_key_name }}"
    wait: true
    nics:
      - net-name: int_network
    userdata: "{{ os_userdata }}"
  register: instanceip
  delegate_to: localhost

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: true
    server: "{{ os_name }}"
    network: ext_network
    wait: true
    timeout: 180
  register: instancefloatingip
  delegate_to: localhost

- name: Wait for server to be available
  wait_for:
    host: "{{ instancefloatingip.floating_ip.floating_ip_address }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600
  delegate_to: localhost
