---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
    server: "{{ os_name }}"
  delegate_to: localhost

- debug: var=openstack_servers
