---
# used to loop over the cloud credentials
- name: "{{ cred.name }}: Check for existing credential"
  uri:
    url: https://tower1.{{ tower_GUID }}.example.opentlc.com/api/v2/credentials?name={{ cred.name }}
    user: "{{ user_name }}"
    password: "{{ password }}"
    force_basic_auth: true
    validate_certs: false
    method: GET
  register: tower_cred_lookup_result

- name: "{{ cred.name }}: Set fact for whether result was found"
  set_fact:
    tower_cred_found: "{{ true if tower_cred_lookup_result.json.count == 1 else false }}"

- name: "{{ cred.name }}: Create New Credential"
  when: not tower_cred_found
  block:
    - name: "{{ cred.name }}: Get Organization ID"
      uri:
        url: "https://tower1.{{ tower_GUID }}.example.opentlc.com/api/v2/organizations?name={{ cred.organization }}"
        user: "{{ user_name }}"
        password: "{{ password }}"
        force_basic_auth: true
        validate_certs: false
        method: GET
      register: tower_cred_org_lookup_result

    - name: "{{ cred.name }}: Get Credential Type ID"
      uri:
        url: "https://tower1.{{ tower_GUID }}.example.opentlc.com/api/v2/credential_types?name={{ cred.credential_type }}"
        user: "{{ user_name }}"
        password: "{{ password }}"
        force_basic_auth: true
        validate_certs: false
        method: GET
      register: tower_cred_type_lookup_result

    - name: "{{ cred.name }}: Set organization ID fact"
      set_fact:
        tower_org_id: "{{ tower_cred_org_lookup_result.json.results[0].id }}"
        tower_cred_type_id: "{{ tower_cred_type_lookup_result.json.results[0].id }}"

    - name: "{{ cred.name }}: Create credential"
      uri:
        url: "https://tower1.{{ tower_GUID }}.example.opentlc.com/api/v2/credentials/"
        user: "{{ user_name }}"
        password: "{{ password }}"
        force_basic_auth: true
        validate_certs: false
        method: POST
        body_format: json
        status_code:
          - 200
          - 201
        body:
          name: "{{ cred.name }}"
          description: "{{ cred.description | default('') }}"
          organization: "{{ tower_org_id }}"
          credential_type: "{{ tower_cred_type_id }}"
          inputs: "{{ cred.inputs }}"

- name: "{{ cred.name }}: Update Credential"
  when: tower_cred_found
  uri:
    url: "https://tower1.{{ tower_GUID }}.example.opentlc.com/api/v2/credentials/{{ tower_cred_lookup_result.json.results[0].id }}/"
    user: "{{ user_name }}"
    password: "{{ password }}"
    force_basic_auth: true
    validate_certs: false
    method: PATCH
    body_format: json
    body:
      description: "{{ cred.description | default('') }}"
      inputs: "{{ cred.inputs }}"
