- name: Create Homework Assignment project 
  tower_project:
    name: "{{ proj_name }}"
    scm_branch: "{{ scm_branch }}"
    scm_url: "{{ scm_url }}"
    state: present
    scm_type: git
    organization: "{{ org_name }}"
    tower_host: "tower1.{{ tower_GUID }}.example.opentlc.com"
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"

- name: Machine Credential to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    state: present
    kind: ssh
    organization: "{{ org_name }}"
    tower_host: "tower1.{{ tower_GUID }}.example.opentlc.com"
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    ssh_key_data: /root/.ssh/openstack.pem
    username: cloud-user

- name: Create Inventory
  tower_inventory:
    organization: "{{ org_name }}"
    tower_host: "tower1.{{ tower_GUID }}.example.opentlc.com"
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    name: "{{ static_inventory_name }}"

- name: Create Group in static inventory 
  tower_group:
    tower_host: "tower1.{{ tower_GUID }}.example.opentlc.com"
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    inventory: "{{ static_inventory_name }}"
    name: "{{ group_name }}"

- name: Add workstation host in tower_inventory 
  tower_host:
    tower_host: "tower1.{{ tower_GUID }}.example.opentlc.com"
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    inventory: "{{ static_inventory_name }}"
    name: "{{ host_name }}"

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{ host_name }}" --group "{{ group_name }}"

- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no
    ssh_key_data: "{{ path_to_opentlc_key }}"
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent
