---
# vars file for roles/config-tower
org_name: Default
scm_branch: master
scm_url: "{{ github_repo }}"
proj_name: "Homework Assignment"
user_name: admin
password: r3dh4t1!
ssh_cred_name: "Connect_to_workstation"
user_cred_name: "cloud-user"
user_cred_path: "/root/.ssh/openstack.pem"
static_inventory_name: scm_inventory
instance_group_name: osp
workflow_template_name: cicd_workflow
job_template_name_osp_instances: "Provision QA Env"
osp_instances_playbook: site-osp-instances.yml
group_name: workstation
host_name: workstation-{{osp_GUID}}.rhpds.opentlc.com
job_template_name_3tier_app: "3tier app deployment on QA Env"
app_deploy_playbook: site-3tier-app.yml
vault_name: yum_repo_vault
job_template_name_osp_instances_delete: "Nuke QA Env"
osp_instances_delete_playbook: site-osp-delete.yml
job_template_smoke_osp: "Smoke test QA Env"
osp_smoke_playbook: site-smoke-osp.yml
job_template_aws_provision: "Provision Prod Env"
aws_provision_playbook: aws_provision.yml
ec2_dynamic_inventory: "Three tier inventory"
aws_ssh_playbook: aws_creds.yml
opentlc_cred_name: "Opentlc key"
job_template_aws_ssh_keys: "SSH keys three tier app"
ec2_inventory_source: "Three tier inventory source"
aws_region_name: "{{ REGION_NAME }}"
tag_filters: "tag:instance_filter=three-tier-app-{{ EMAIL }}"
scm_inventory_source: "SCM three tier inventory source"
path_to_scm_inventory: scm_inventory
aws_read_keys: "AWS Access Key"
aws_status_playbook: aws_status_check.yml
job_template_aws_status_check: "Check the status of AWS instances"
job_template_name_3tier_app_aws: "3 tier app on Prod"
aws_cred_name: "Creds for AWS instances"
job_template_smoke_aws: "Smoke test Prod env"
aws_smoke_app_playbook: site-smoketest-aws.yml

tower_inventories:
  - name: "{{ static_inventory_name }}"
  - name: qa
    sources:
      - name: qa_scm
        source: scm
        source_project: "{{ proj_name }}"
        source_path: inventories/qa/hosts

tower_credential_types:
  - name: OpenTLC
    kind: cloud
    description: OpenTLC Credentials
    inputs:
      fields:
        - type: string
          id: username
          label: Username
        - type: string
          id: password
          label: Password
          secret: true
    injectors:
      extra_vars:
        # This forces the jinja in the string to not be enumerated.
        param_password: !unsafe "{{ password }}"
        param_user: !unsafe "{{ username }}"

tower_credentials:
  - name: yum-repo-cred
    organization: "{{ org_name }}"
    kind: vault
    vault_password: ansible
  - name: opentlc
    organization: "{{ org_name }}"
    kind: cloud
    credential_type: OpenTLC
    inputs:
      username: "{{ opentlc_login }}"
      password: "{{ opentlc_password }}"

tower_job_templates:
  - name: "{{job_template_name_osp_instances}}"
    job_type: run
    inventory: "{{ static_inventory_name}}"
    project: "{{ proj_name }}"
    playbook: "{{ osp_instances_playbook }}"
    credential: "{{ ssh_cred_name }}"
    instance_group: "{{instance_group_name}}"
  - name: "{{ job_template_name_3tier_app }}"
    job_type: run
    inventory: qa
    project: "{{ proj_name }}"
    playbook: "{{ app_deploy_playbook }}"
    credential: "{{ ssh_cred_name }}"
    vault_credential: yum-repo-cred
    instance_group: "{{instance_group_name}}"
  - name: "{{ job_template_name_osp_instances_delete }}"
    job_type: run
    inventory: qa
    project: "{{ proj_name }}"
    playbook: "{{ osp_instances_delete_playbook }}"
    credential: "{{ ssh_cred_name }}"
    instance_group: "{{ instance_group_name }}"
  - name: "{{job_template_smoke_osp}}"
    job_type: run
    inventory: "{{ static_inventory_name }}"
    project: "{{ proj_name }}"
    playbook: "{{ osp_smoke_playbook }}"
    credential: "{{ssh_cred_name}}"
    instance_group: "{{ instance_group_name }}"
  - name: "{{job_template_aws_provision}}"
    job_type: run
    inventory: "{{ static_inventory_name }}"
    project: "{{ proj_name }}"
    playbook: "{{aws_provision_playbook}}"
    credential: "{{ssh_cred_name}}"
    extra_vars_path: "/tmp/aws_jq_vars.yml"
  - name: "{{job_template_aws_ssh_keys}}"
    job_type: run
    inventory: "{{ static_inventory_name }}"
    project: "{{ proj_name }}"
    playbook: "{{ aws_ssh_playbook }}"
    credential: "{{opentlc_cred_name}}"
    extra_vars_path: "/tmp/tower_info.yml"
  - name: "{{ job_template_aws_status_check }}"
    job_type: run
    inventory: "{{ ec2_dynamic_inventory }}"
    project: "{{ proj_name }}"
    playbook: "{{aws_status_playbook}}"
    credential: "{{ opentlc_cred_name }}"
  - name: "{{ job_template_name_3tier_app_aws }}"
    job_type: run
    inventory: "{{ ec2_dynamic_inventory }}"
    project: "{{ proj_name }}"
    playbook: "{{app_deploy_playbook}}"
    vault_credential: yum-repo-cred
  - name: "{{job_template_smoke_aws}}"
    job_type: run
    inventory: "{{ ec2_dynamic_inventory }}"
    project: "{{ proj_name }}"
    playbook: "{{ aws_smoke_app_playbook }}"
    vault_credential: yum-repo-cred
