name: basic

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Ansible
      run: |
        pip install ansible
    - name: Run a multi-line script
      run: |
        ls -al
        ansible-playbook cd-update-tower.yml
