name: basic
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Ansible
      run: |
        pip install wheel ansible
    - name: Execute Ansible Playbook
      run: |
        ls -al
        ansible-playbook cd-update-tower.yml
